siteTitle = 'Món Ngon Ngừa Bệnh'
siteDescr = 'Điểm Tâm'
siteDescription = "Hãy ăn uống ngay"
siteUrl = "http://caythuocnguabenh.net"
siteBandcampUrl = 'http://caythuocnguabenh.net'
siteMenuOne = 'Món Phụ'
siteMenuTwo = 'Món Chính'
siteMenuThree = 'Thực Đơn'
siteAddress = 'Ấp Bãi Vòng, Xã Hàm Ninh, Thành phố Phú Quốc'
siteAddress2 = 'Tỉnh Kiên Giang, Việt Nam. Postal code 920000'

siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/MonNgonBinhDuong2018'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/OdayakaPhuQuoc'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com'
siteYoutubeUrl = 'https://www.youtube.com/channel/UC2xhVmkOYPKibhJm3f0f3hw'

linkPrefix = '/'
